<?php

namespace Container6R7QAM2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBankimgFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BankimgFormType' shared autowired service.
     *
     * @return \App\Form\BankimgFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/BankimgFormType.php';

        return $container->privates['App\\Form\\BankimgFormType'] = new \App\Form\BankimgFormType();
    }
}
