controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

front_index:
    path: /
    controller: App\Controller\FrontController::index
