controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

front_index:
    path: /
    controller: App\Controller\FrontController::index
accueil_index:
    path: /accueil
    controller: App\Controller\FrontController::index
contact:
    path: /contact
    controller: App\Controller\FrontController::contact
admin:
    path: /admin-data-dev
    controller: App\Controller\AdminController::login
dashboard:
    path: /dashboard
    controller: App\Controller\AdminController::dashboard
logout:
    path: /logout
    controller: App\Controller\AdminController::logout