controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

front_index:
    path: /
    controller: App\Controller\FrontController::index
accueil_index:
    path: /accueil
    controller: App\Controller\FrontController::index
1content_index:
    path: /tout-sur-la-peche
    controller: App\Controller\FrontController::content1
2content_index:
    path: /infos-nosy-be
    controller: App\Controller\FrontController::content2
3content_index:
    path: /peche-autour-de-nosy-be
    controller: App\Controller\FrontController::content3
4content_index:
    path: /peche-jour-mitsio
    controller: App\Controller\FrontController::content4
5content_index:
    path: /sejour-avec-hotel-peche-mitsio-8jours
    controller: App\Controller\FrontController::content5
contact:
    path: /contact
    controller: App\Controller\FrontController::contact
admin:
    path: /admin-data-dev
    controller: App\Controller\AdminController::login
dashboard:
    path: /dashboard
    controller: App\Controller\AdminController::dashboard
logout:
    path: /logout
    controller: App\Controller\AdminController::logout
apidatadev:
    path: /api-data-dev
    controller: App\Controller\ApiController::updateimage
