controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

front_index:
    path: /
    controller: App\Controller\FrontController::index
accueil_index:
    path: /accueil
    controller: App\Controller\FrontController::index
contact:
    path: /contact
    controller: App\Controller\FrontController::contact
test:
    path: /test
    controller: App\Controller\FrontController::test