<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnFlBdc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnFlBdc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKnFlBdc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKnFlBdc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKnFlBdc\App_KernelDevDebugContainer([
    'container.build_hash' => 'KnFlBdc',
    'container.build_id' => 'd7eb3756',
    'container.build_time' => 1723017381,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnFlBdc');
