<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRJa4uQJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRJa4uQJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRJa4uQJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRJa4uQJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRJa4uQJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'RJa4uQJ',
    'container.build_id' => '4a1753ec',
    'container.build_time' => 1718688017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRJa4uQJ');
