<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7tLhGTq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7tLhGTq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7tLhGTq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7tLhGTq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7tLhGTq\App_KernelDevDebugContainer([
    'container.build_hash' => '7tLhGTq',
    'container.build_id' => '1ef3b81f',
    'container.build_time' => 1716744356,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7tLhGTq');
